/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author anton
 */
public class Compras extends javax.swing.JPanel {

    /**
     * Creates new form Compras
     */
    public Compras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_compra_activos = new javax.swing.JComboBox<>();
        txt_compra_autor = new com.goslinggroup.utilsui.TextField();
        cbx_compra_estado = new javax.swing.JComboBox<>();
        btn_compra_guardar = new javax.swing.JButton();
        btn_compra_actualizar = new javax.swing.JButton();
        btn_compra_eliminar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tabla_compras = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_compra_activos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar activo", " " }));
        cbx_compra_activos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_compra_activosActionPerformed(evt);
            }
        });
        add(cbx_compra_activos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 240, 40));

        txt_compra_autor.setLabelText("Autor de compra");
        add(txt_compra_autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 240, -1));

        cbx_compra_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar estado", " " }));
        add(cbx_compra_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 240, 50));

        btn_compra_guardar.setText("Guardar");
        add(btn_compra_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 100, 40));

        btn_compra_actualizar.setText("Actualizar");
        add(btn_compra_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 100, 40));

        btn_compra_eliminar.setText("Eliminar");
        add(btn_compra_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 100, 40));

        tabla_compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tabla_compras);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 700, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_compra_activosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_compra_activosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_compra_activosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_compra_actualizar;
    private javax.swing.JButton btn_compra_eliminar;
    private javax.swing.JButton btn_compra_guardar;
    private javax.swing.JComboBox<String> cbx_compra_activos;
    private javax.swing.JComboBox<String> cbx_compra_estado;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tabla_compras;
    private com.goslinggroup.utilsui.TextField txt_compra_autor;
    // End of variables declaration//GEN-END:variables
}
