/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

/**
 *
 * @author anton
 */
public class Empleados extends javax.swing.JPanel {

    /**
     * Creates new form Empleados
     */
    public Empleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbx_empleado_cargo = new javax.swing.JComboBox<>();
        txt_empleado_dni = new com.goslinggroup.utilsui.TextField();
        txt_empleado_nombre = new com.goslinggroup.utilsui.TextField();
        txt_empleado_apellido = new com.goslinggroup.utilsui.TextField();
        btn_empleado_guardar = new javax.swing.JButton();
        btn_empleado_actualizar = new javax.swing.JButton();
        btn_empleado_eliminar = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabla_empleados = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_empleado_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar cargo" }));
        add(cbx_empleado_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 69, 240, 42));

        txt_empleado_dni.setLabelText("DNI de empleado");
        add(txt_empleado_dni, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 129, 240, -1));

        txt_empleado_nombre.setLabelText("Nombres de empleado");
        add(txt_empleado_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 240, -1));

        txt_empleado_apellido.setLabelText("Apellidos de empleado");
        add(txt_empleado_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 240, -1));

        btn_empleado_guardar.setText("Guardar");
        add(btn_empleado_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 40));

        btn_empleado_actualizar.setText("Actualizar");
        add(btn_empleado_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 140, 40));

        btn_empleado_eliminar.setText("Eliminar");
        add(btn_empleado_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 140, 40));

        tabla_empleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(tabla_empleados);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 800, 380));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_empleado_actualizar;
    private javax.swing.JButton btn_empleado_eliminar;
    private javax.swing.JButton btn_empleado_guardar;
    private javax.swing.JComboBox<String> cbx_empleado_cargo;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tabla_empleados;
    private com.goslinggroup.utilsui.TextField txt_empleado_apellido;
    private com.goslinggroup.utilsui.TextField txt_empleado_dni;
    private com.goslinggroup.utilsui.TextField txt_empleado_nombre;
    // End of variables declaration//GEN-END:variables
}
