/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.border.CompoundBorder;

/**
 *
 * @author anton
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        panelRegistra.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelIniciar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textField1 = new com.goslinggroup.utilsui.TextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPasswordField2 = new javax.swing.JPasswordField();
        lblRegistrar = new javax.swing.JLabel();
        panelRegistra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnombres = new com.goslinggroup.utilsui.TextField();
        txtapellidos = new com.goslinggroup.utilsui.TextField();
        txtemail = new com.goslinggroup.utilsui.TextField();
        txtpass = new com.goslinggroup.utilsui.TextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(910, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelIniciar.setBackground(new java.awt.Color(255, 255, 255));
        panelIniciar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(15, 154, 198));
        jLabel4.setText("INICIAR SESIÓN");
        panelIniciar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        textField1.setLabelText("Email");
        panelIniciar.add(textField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 260, -1));

        jButton2.setIcon(new ImageIcon("src/main/java/imagenes/btniniciarsesion.png"));
        jButton2.setAutoscrolls(true);
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        panelIniciar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 140, 30));

        jButton3.setForeground(new java.awt.Color(51, 153, 255));
        jButton3.setText("Iniciar Sesión");
        jButton3.setAutoscrolls(true);
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255), 2));
        jButton3.setContentAreaFilled(false);
        panelIniciar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 140, 30));

        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        panelIniciar.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 260, 40));

        jPanel1.add(panelIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 380, 500));

        lblRegistrar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setText("Registrase");
        lblRegistrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 130, 30));

        panelRegistra.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistra.setPreferredSize(new java.awt.Dimension(430, 530));
        panelRegistra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(15, 154, 198));
        jLabel2.setText("REGÍSTRATE");
        panelRegistra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        txtnombres.setLabelText("Nombres");
        panelRegistra.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 230, -1));

        txtapellidos.setLabelText("Apellidos");
        panelRegistra.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 230, -1));

        txtemail.setLabelText("Email");
        panelRegistra.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 230, -1));

        txtpass.setLabelText("Password");
        panelRegistra.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 230, -1));

        jButton1.setIcon(new ImageIcon("src/main/java/imagenes/btnregistrar.png"));
        jButton1.setAutoscrolls(true);
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        panelRegistra.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 90, 30));

        jPanel1.add(panelRegistra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 390, 510));
        panelRegistra.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setIcon(new ImageIcon("src/main/java/imagenes/Rectangle2.png"));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 380, 510));

        jLabel1.setIcon(new ImageIcon("src/main/java/imagenes/Rectangle1.png"));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        int posicion = lblRegistrar.getX();
        if(posicion > 126){
            Animacion.Animacion.mover_izquierda(381, 125, 3, 3, lblRegistrar);
            Animacion.Animacion.mover_izquierda(20, -480, 3, 3, panelIniciar);
            panelRegistra.setVisible(true);
            lblRegistrar.setText("Iniciar Sesion");
            lblRegistrar.setForeground(Color.decode("#0F9AC6"));
            lblRegistrar.setBorder(new CompoundBorder(
                BorderFactory.createMatteBorder(2, 2, 2, 2, Color.decode("#0F9AC6")),
                BorderFactory.createEmptyBorder(2, 2, 2, 2)));
        }else{
            Animacion.Animacion.mover_derecha(25, 545, 3, 3, lblRegistrar);
            Animacion.Animacion.mover_derecha(-180, 70, 3, 3, panelIniciar);
            panelRegistra.setVisible(false);
            lblRegistrar.setText("Registrase");
            lblRegistrar.setForeground(Color.WHITE);
            lblRegistrar.setBorder(new CompoundBorder(
                BorderFactory.createMatteBorder(2, 2, 2, 2, Color.WHITE),
                BorderFactory.createEmptyBorder(2, 2, 2, 2)));
        }
    }//GEN-LAST:event_lblRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JPanel panelIniciar;
    private javax.swing.JPanel panelRegistra;
    private com.goslinggroup.utilsui.TextField textField1;
    private com.goslinggroup.utilsui.TextField txtapellidos;
    private com.goslinggroup.utilsui.TextField txtemail;
    private com.goslinggroup.utilsui.TextField txtnombres;
    private com.goslinggroup.utilsui.TextField txtpass;
    // End of variables declaration//GEN-END:variables
}
